### ISSUE TITLE
iTerm image support

### ISSUE THREAD

**Issue by brandondrew** [piotrmurach/tty-pie_chart#2]
This is mega-cool, and speaks to how complete the TTY toolkit is.  However, if I were ever generating pie charts in the terminal, I would want to take advantage of iTerm's support for real (non-ASCII) images.  

There is undoubtedly already a library out there to generate the images. How hard would it be to use it to generate images that are shown instead of ASCII graphics when iTerm (or any other terminal emulator that supports images) is detected?

**Comment by piotrmurach** [comment]
Hi Brandon,

Good to hear from yourself again as we had some interesting conversation on the queen project. 

Let me step back a little bit to explain the 'philosophy' behind tty gems. There is a multitude of terminal emulators and different operating systems. What connects them is usually quite a brittle standard. I aim to achieve compatibility by using a minimum amount of standards and most expressive API so that people can create libraries that are portable and work in as many environments as possible. There is a balance between having great looking chart and realistic image quality chart. 

The `tty-pie_chart` allows you to use any non-ascii characters, actually, the default screenshot is done using `unicode dot` character. Nothing prevents you to use emoji and any other chars to fill the chart. However, if you intend for the library to be used by devs then probably you would err on the side of caution. 

I don't know how to reliably detect if terminals can render images and I'm not sure how would that be applicable to this library?
